### NUMPY

- contents
    - why?
    - creating numpy Arrays
    - Attributes
    - Subsetting,string Indexing
    - Array manipulation
    - Vectorize function
    - Mathematical operations,Broadcasting
    - Statistical functions,Trignometric functions,Logarithmetic functions
    - Linear Algebraic Funtions
    - Reading image data into numpy array
    - Reading sklearn datasets as numpy array

In [2]:
import numpy

In [3]:
numpy.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy as np
np.__version__

'1.15.4'

In [5]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [6]:
from numpy import * # all the modules and sub packages will be imported

### Numpy Array Creation from 
- List
- Tuple
- range

In [8]:
np.array([23,45,67])

array([23, 45, 67])

In [9]:
np.array((1,2,3))

array([1, 2, 3])

In [10]:
np.array(range(5,10))

array([5, 6, 7, 8, 9])

In [11]:
a=np.array(range(5,10))
print(a)
print(type(a))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [17]:
print(a.shape) # tuple
print(a.dtype) # datatype
print(a.size) # no of elements
print(a.itemsize) # no of bytes for each item
print(a.ndim) # no of dimensions
print(a.nbytes) #Total array size in bytes a.size*a.itemsize

(5,)
int32
5
4
1
20


In [13]:
l=[1]
t=(1,)
print(type(l),type(t))

<class 'list'> <class 'tuple'>


In [15]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
print(a2.shape) # tuple
print(a2.dtype) # datatype
print(a2.size) # no of elements
print(a2.itemsize) # no of bytes for each item
print(a2.ndim) # no of dimensions
print(a2.nbytes) #Total array size in bytes a.size*a.itemsize

(3, 3)
int32
9
4
2
36


In [23]:
print(a2.shape[1])

3


In [20]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [24]:
np.array([1,2,3,7],dtype=np.int8)

array([1, 2, 3, 7], dtype=int8)

In [26]:
a3=(((1,2,3),(4,5,6)))
a3

((1, 2, 3), (4, 5, 6))

In [28]:
a4=np.array([1,2,3,4,312],dtype=np.int8)
print(a4.shape) # tuple
print(a4.dtype) # datatype
print(a4.size) # no of elements
print(a4.itemsize) # no of bytes for each item
print(a4.ndim) # no of dimensions
print(a4.nbytes) #Total array size in bytes a.size*a.itemsize

(5,)
int8
5
1
1
5


In [25]:
a5=np.array([1,2,3,7,(2**32)+1])
print(a5.dtype)

int64


In [31]:
a6=np.array([1,'kavya',90])
print(a6.dtype)

<U11


In [33]:
a7=np.array([12,3,4,None])
print(a7.dtype)
print(type(a[0]))

object
<class 'numpy.int32'>


In [34]:
a8=np.array([1,2,3,4,np.nan])
print(a8.dtype)

float64


### Initializing arrays
- zeroes
- ones
- full
- eye
- diag

In [38]:
help(ones)

Help on function ones in module numpy.core.numeric:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
   

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.ones((2,3),bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [39]:
np.array(2,3,bool)

ValueError: only 2 non-keyword arguments accepted

In [41]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [6]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled wi

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
import numpy as np
help(np.diag)

Help on function diag in module numpy.lib.twodim_base:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the 

In [2]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

I

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [12]:
np.arange(5,10,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [20]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

- [] 
    - both are inclusive
- [)
- (]
- ()

In [19]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [21]:
np.linspace(5,10,5,10)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

### Mathematical operations

In [8]:
a=np.arange(5)
b=np.ones(5)
print(a)
print(b)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]


In [9]:
print(a+b) # element-wise addition
print(a-b) # element-wise subtraction
print(a*b) # element-wise multiplication
print(a/b) # element-wise division
print(a%b) # element-wise modulo division
print(a//b) # element-wise floor division

[1. 2. 3. 4. 5.]
[-1.  0.  1.  2.  3.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 0. 0. 0. 0.]
[-0.  1.  2.  3.  4.]


In [11]:
print(a**2)
print(a*2)
print(a+2) 
print(a-2) 
print(a/2) 

[ 0  1  4  9 16]
[0 2 4 6 8]
[2 3 4 5 6]
[-2 -1  0  1  2]
[0.  0.5 1.  1.5 2. ]


### Random

In [12]:
np.random.randint(100)

32

In [13]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [14]:
np.random.randint(100, size=(5, 2))

array([[61,  1],
       [81,  3],
       [25, 31],
       [30, 93],
       [62, 66]])

In [15]:
np.random.randint(50,100, size=(5, 2))

array([[72, 99],
       [68, 66],
       [52, 50],
       [59, 50],
       [84, 94]])

In [16]:
np.random.random()

0.7772786512423565

In [17]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [18]:
np.random.random(10)

array([0.7942366 , 0.39329536, 0.11402081, 0.38181918, 0.91609218,
       0.0513819 , 0.58034351, 0.30962878, 0.11444039, 0.20155568])

In [20]:
np.random.random((2,3))

array([[0.24571198, 0.67910659, 0.89483533],
       [0.84258626, 0.10867324, 0.81143817]])

In [21]:
np.random.rand()

0.04206787544592483

In [22]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]

In [25]:
np.random.rand(3)

array([0.24815145, 0.30130809, 0.34028315])

In [26]:
np.random.rand(2,5)

array([[0.93654944, 0.47234313, 0.23910074, 0.66980367, 0.69584929],
       [0.90843727, 0.22561674, 0.49265288, 0.63633982, 0.35051899]])

In [28]:
np.random.random((2,5))

array([[0.59459728, 0.94214383, 0.40422328, 0.96035787, 0.80397879],
       [0.12206791, 0.79448301, 0.79972209, 0.49210647, 0.25759598]])

In [29]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'info',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [30]:
help(np.random.shuffle)

Help on built-in function shuffle:

shuffle(...) method of mtrand.RandomState instance
    shuffle(x)
    
    Modify a sequence in-place by shuffling its contents.
    
    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.
    
    Parameters
    ----------
    x : array_like
        The array or list to be shuffled.
    
    Returns
    -------
    None
    
    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8]
    
    Multi-dimensional arrays are only shuffled along the first axis:
    
    >>> arr = np.arange(9).reshape((3, 3))
    >>> np.random.shuffle(arr)
    >>> arr
    array([[3, 4, 5],
           [6, 7, 8],
           [0, 1, 2]])



In [34]:
r=np.arange(10,20)
np.random.shuffle(r)
print(r)

[16 13 15 12 11 17 10 18 19 14]


### Array manipulation

In [35]:
a=np.arange(20)
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [40]:
a.reshape(13,2)

ValueError: cannot reshape array of size 20 into shape (13,2)

In [39]:
a.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [41]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
a.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
a.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [44]:
a.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [45]:
help(np.resize)

Help on function resize in module numpy.core.fromnumeric:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Examples
    --------
    >>> a=np.array([[0,1],[2,3]])
    >>> np.resize(a,(2,3))
    array([[0, 1, 2]

In [46]:
np.resize(a,(13,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [49]:
z=np.arange(20)
z.resize(13,2)
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

In [50]:
np.expand_dims(a,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [51]:
np.expand_dims(a,0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [54]:
a2=np.arange(10).reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
y=np.expand_dims(a2,1)

In [66]:
y.shape

(2, 1, 5)

In [69]:
x=np.expand_dims(a2,0)

In [68]:
x.shape

(1, 2, 5)

### Flatten

In [72]:
a2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.expand_dims(a2,0).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Iteration over 1D,2D and 3D arrays

In [78]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
for i in a:
    print(i)
    break

0


In [81]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
for i in a2:
    print(i)
    break

[0 1 2 3 4]


In [80]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [77]:
for i in np.arange(12).reshape(2,2,3):
    print(i)
    break

[[0 1 2]
 [3 4 5]]


### Indexing,slicing and subset

In [83]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [84]:
print(a[0])
print(a[-1])

0
19


In [85]:
print(a[2:10])
print(a[2:12:3])

[2 3 4 5 6 7 8 9]
[ 2  5  8 11]


In [86]:
print(a[[1,10,3]])

[ 1 10  3]


### Fancy indexing

In [87]:
a % 2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [88]:
a[a % 2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
a[[True,False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 20 but corresponding boolean dimension is 2

In [101]:
a[[True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False,True,False]]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
a2=np.arange(20).reshape(5,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [92]:
a2[0]

array([0, 1, 2, 3])

In [93]:
a2[-1]

array([16, 17, 18, 19])

In [94]:
a2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
# reverse
a2[[4,3,2,1,0]]

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [97]:
# print 1,4,5 rows
a2[[True,False,False,True,True]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [98]:
a2[2,2]

10

- rows
   - 0,1,2,3,4
- columns
   - 0,1,2,3

In [102]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [103]:
print(a2[2,2])
print(a2[2][2])

10
10


In [104]:
a2[3,3]

15

In [105]:
a2[1:4,2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [109]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [111]:
a2[3:5,2:4]

array([[14, 15],
       [18, 19]])

In [113]:
a2[[1,3,2],[3,2,1]] #(1,3),(3,2),(2,1)

array([ 7, 14,  9])