### NUMPY TIME COMPARISION

In [1]:
import time
import numpy as np
start=time.time()
l=[x*x for x in range(100000)]
end=time.time()
print('time with lists: ',end-start)
start=time.time()
a=np.arange(100000)
a=a*a
end=time.time()
print('time with np arrays: ',end-start)

time with lists:  0.01397252082824707
time with np arrays:  0.09894371032714844


### Trignometric Functions

In [2]:
a=np.random.randint(100,size=23)
np.sin(a)

array([-0.82181784,  0.55142668, -0.26237485, -0.42818267,  0.68326171,
        0.01770193,  0.67022918,  0.83665564,  0.10598751,  0.74511316,
        0.14112001,  0.1673557 , -0.99975517, -0.90557836, -0.53657292,
        0.99060736,  0.1673557 ,  0.68326171, -0.67677196,  0.89399666,
       -0.44411267, -0.7391807 ,  0.90929743])

In [3]:
np.sin(3.14/2)

0.9999996829318346

In [4]:
np.arcsin(1)

1.5707963267948966

In [8]:
np.deg2rad(90)

1.5707963267948966

In [9]:
np.rad2deg(1.5707963267948966) # to convert radiance to degree

90.0

In [6]:
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [7]:
math.sin([2,3])

TypeError: must be real number, not list

### Log and Exponential functions

In [12]:
print(np.log(2))
print(np.log(1))
print(np.log(np.exp(1)))

0.6931471805599453
0.0
1.0


In [13]:
print(np.log2(2))
print(np.log2(32))

1.0
5.0


In [14]:
print(np.log(0))

-inf


C:\Users\sivar\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [16]:
np.log1p(2) # np.log1p(x)=np.log(1+x)

1.0986122886681098

In [17]:
np.log(2+1)

1.0986122886681098

In [21]:
np.exp(1)
np.exp2(2)

4.0

In [25]:
print(np.expm1(5))
print(np.exp(5)-1)
# np.expm1(x)=np.exp(x)-1

147.4131591025766
147.4131591025766


### Statistics

In [29]:
a=np.random.randint(100,size=5)
a

array([12, 35, 22, 99, 48])

In [31]:
print(a.sum())
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

216
216
43.2
35.0
30.419730439305344


In [33]:
print(np.sort(a))

[12 22 35 48 99]


In [34]:
print(np.quantile(a,0.25))
print(np.quantile(a,0.5))
print(np.quantile(a,0.75))

22.0
35.0
48.0


### BroadCasting

In [37]:
a=np.arange(5)
b=np.arange(4)
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [38]:
a=np.arange(10).reshape(5,2)
b=np.arange(2)
a+b

array([[ 0,  2],
       [ 2,  4],
       [ 4,  6],
       [ 6,  8],
       [ 8, 10]])

In [39]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
b

array([0, 1])

In [41]:
a=np.arange(10).reshape(5,2)
b=np.arange(5)
a+b

ValueError: operands could not be broadcast together with shapes (5,2) (5,) 

In [46]:
x=np.arange(15).reshape(3,5,1)
y=np.arange(5)
x+y

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8]],

       [[ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10],
        [ 7,  8,  9, 10, 11],
        [ 8,  9, 10, 11, 12],
        [ 9, 10, 11, 12, 13]],

       [[10, 11, 12, 13, 14],
        [11, 12, 13, 14, 15],
        [12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18]]])

In [51]:
x=np.arange(15).reshape(5,3)
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

105
[30 35 40]
[ 3 12 21 30 39]


In [53]:
np.random.seed(5)
a=np.random.randint(50,size=10)
b=np.random.randint(50,size=10)
print(a)
print(b)

[35 14 47 38 16  9  8 36 39 27]
[48 30 16  7 12 15 49 39 16 27]


In [54]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or 1-d array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



In [55]:
def maxnumber(n1,n2):
    if n1>n2:
        return n1
    else:
        return n2
maxnumber(5,44)

44

In [56]:
maxnumber_vec=np.vectorize(maxnumber)
maxnumber_vec(a,b)

array([48, 30, 47, 38, 16, 15, 49, 39, 39, 27])

### Stacking

In [2]:
import numpy as np
a=np.arange(6)
b=np.arange(6)
np.hstack([a,b]) # no of rows should be equal

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [3]:
np.vstack([a,b]) # no of columns should be equal

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [4]:
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(2,3)
np.hstack([a,b])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [6]:
a=np.arange(6).reshape(2,3)
b=np.arange(3)
np.vstack([a,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

### Linear Algebra

In [7]:
np.linalg.det(np.eye(2))

1.0

In [8]:
np.linalg.det(np.array([[1,2],[3,4]]))

-2.0000000000000004

In [10]:
np.linalg.inv(np.array([[1,2],[5,7]]))

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [11]:
np.linalg.matrix_rank(np.array([[1,2],[5,7]]))

2

- np.dot
- np.matmul

In [15]:
x=np.array([[1,2],[5,7]])
y=np.array([[4,1],[2,2]])
np.matmul(x,y)

array([[ 8,  5],
       [34, 19]])

In [16]:
np.matmul(y,x)

array([[ 9, 15],
       [12, 18]])

In [19]:
np.dot(x,y)

array([[ 8,  5],
       [34, 19]])

In [20]:
np.dot(y,x)

array([[ 9, 15],
       [12, 18]])

### Email validator

In [1]:
import re 
regexp = '^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$'
def check(email):  
    if(re.search(regexp,email)):  
        print("Valid Email")            
    else:  
        print("Invalid Email")  
        
email = input("enter the Email Id: ") 
check(email) 

enter the Email Id: kavyathata@gmail.com
Valid Email


####  Email Addresses 
- ^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$

- The position anchors ^ and $ match the beginning and the ending of the input string, respectively. That is, this regex shall match the entire input string, instead of a part of the input string (substring).
- \w+ matches 1 or more word characters (same as [a-zA-Z0-9_]+).
- [.-]? matches an optional character . or -. Although dot (.) has special meaning in regex, in a character class (square brackets) any characters except ^, -, ] or \ is a literal, and do not require escape sequence.
- ([.-]?\w+)* matches 0 or more occurrences of [.-]?\w+.
- The sub-expression \w+([.-]?\w+)* is used to match the username in the email, before the @ sign. It begins with at least one word character [a-zA-Z0-9_], followed by more word characters or . or -. However, a . or - must follow by a word character [a-zA-Z0-9_]. That is, the input string cannot begin with . or -; and cannot contain "..", "--", ".-" or "-.". Example of valid string are "a.1-2-3".
- The @ matches itself. In regex, all characters other than those having special meanings matches itself, e.g., a matches a, b matches b, and etc.
- Again, the sub-expression \w+([.-]?\w+)* is used to match the email domain name, with the same pattern as the username described above.
- The sub-expression \.\w{2,3} matches a . followed by two or three word characters, e.g., ".com", ".edu", ".us", ".uk", ".co".
- (\.\w{2,3})+ specifies that the above sub-expression could occur one or more times, e.g., ".com", ".co.uk", ".edu.sg" etc.

### Phone number validator

In [7]:
# using functions
import re
regexp= "\\w{3}\\w{3}\w{4}"
def check(phoneno):  
    if(re.search(regexp,phoneno)):  
        print("Valid phone number ")            
    else:  
        print("Invalid phone number")  
        
phoneno= input("enter the number: ")
check(phoneno)

enter the number: 9290570453
Valid phone number 


In [9]:
import re
phonenumber= input('enter the phone number: ')
regex= "\\w{3}\\w{3}\w{4}"
if re.search(regex, phonenumber):
    print("Valid phone number")
else:
    print("Invalid phone number")

enter the phone number: 9553941253
Valid phone number


### Example

In [1]:
import datetime
f=open('data.txt')
data=f.read()
data=eval(data)
data

[{'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 520},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 521},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 523},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 524},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 530},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 531},
 {'attendance': 'A',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 533},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
  'level': 3,
  'student_id': 534},
 {'attendance': 'P',
  'session': 'FN',
  'date': datetime.date(2019, 12, 21),
 

In [2]:
data[0]

{'attendance': 'P',
 'session': 'FN',
 'date': datetime.date(2019, 12, 21),
 'level': 3,
 'student_id': 520}

In [3]:
import datetime
f=open("data.txt")
s=f.read()
l=eval(s)
print(type(l))
s=set()
s1=set()
for i in l:
    s.add(i['student_id'])
    s1.add(i['date'])
s1=list(s1)
s1.sort()

d={}
for i in l:
    if(i['date']==s1[0]):
        if(i['student_id'] not in list(d.keys())):
            d[i['student_id']]=list()
            d[i['student_id']].append(i['attendance'])
        else:
            d[i['student_id']].append(i['attendance'])
    if(i['date']==s1[1]):
        if(i['student_id'] not in list(d.keys())):
            d[i['student_id']]=list()
            d[i['student_id']].append(i['attendance'])
        else:
            d[i['student_id']].append(i['attendance'])
    if(i['date']==s1[2]):
        if(i['student_id'] not in list(d.keys())):
            d[i['student_id']]=list()
            d[i['student_id']].append(i['attendance'])
        else:
            d[i['student_id']].append(i['attendance'])
for i in d.keys():
    if(len(d[i])<6):
        d[i].insert(2,"NA")
    print(d[i])

<class 'list'>
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['A', 'A', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['A', 'A', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'A', 'A']
['P', 'P', 'A', 'A', 'A', 'A']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'A', 'A']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P', 'P']
['P', 'P', 'P', 'P', 'P'